### ISSUE TITLE
SQLSTATE[HY000]: [Microsoft][ODBC Driver 13 for SQL Server]Protocol error in TDS stream 

### ISSUE THREAD

**Issue by webspeaks** [uepg/laravel-sybase#33]
Hi,
When I use this connector to connect with sybase db (SAP ASE) I get the following error:

`SQLSTATE[HY000]: [Microsoft][ODBC Driver 13 for SQL Server]Protocol error in TDS stream`

I have installed all required drivers and extensions in my PHP installation.

OS - Windows 10
Platform- Wampp 64 Bit
PHP - 7.0

Please let me know if you have any idea about this error.

Thanks

**Comment by mainginski** [comment]
At the moment, it is necessary for the package to run in the Linux environment, since it natively uses the dblib connection to the sqlserver. In that case, you can use the Vagrant machine (I as a developer on Windows, I do this). Nothing prevents you from developing using Windows, but you need to create the interface for ODBC, I mentioned something like that in the issue #32, but I did not test it.

**Comment by nunomazer** [comment]
Hi, have you tryied use the dblib driver instead ODBC? Install `php-sybase` and `freetds-bin` packages, and config it as described at https://github.com/uepg/laravel-sybase#configuration-of-freetds-driver

Since we don't use ODBC connections, we still didn't test it in any O.S., Windows or Linux.

**Comment by vkrtecek** [comment]
Check if you have specified right port number. I had 3306 instead of 1433
